-- ============================================
-- SEED DATA — generated by scripts/seed.mjs
-- ============================================

-- Clear existing seed data (idempotent)
DELETE FROM user_to_groups;
DELETE FROM point_transactions;
DELETE FROM permission_groups;
DELETE FROM users;

-- ==================
-- Users
-- ==================
INSERT INTO users (id, email, name, account_role, role, password_hash, created_at, updated_at) VALUES
  ('seed_admin_001', 'admin@example.com', 'Dev Admin', 'admin', 'root',  'daafedf5ed5d31d62ca824fb17077c14:1c4149ce64192e5dddf343552398fc5f0cbfcbd589171591b51d5238b522388c', 1772808478077, 1772808478077),
  ('seed_mod_001',   'mod@example.com',   'Dev Mod',   'user',  'mod',   'b36f8d3b1dc87fc2f7423ae8fe58648b:61fc4d260a6aaad6cc10c4bdf370ac2244335737b4bc5706fcff335ccf66f391',   1772808478077, 1772808478077),
  ('seed_user_001',  'user@example.com',  'Dev User',  'user',  'user',  'c94c0a90c85b9319c56f4a58e606ee61:3ca857ed68ac58a1123d5fa8c06beab14c23f1feeaff93fa2b1c4ed9c5366e5e',  1772808478077, 1772808478077);

-- ==================
-- Permission Groups
-- ==================
INSERT INTO permission_groups (id, name, permissions, created_at) VALUES
  ('seed_grp_creator',  'Standard Creator', '["game:create","game:edit"]', 1772808478077),
  ('seed_grp_supermod', 'Super Mod',        '["game:all","user:moderate","points:grant","xp:grant"]', 1772808478077);

-- ==================
-- User ↔ Group assignments
-- ==================
-- Mod gets Super Mod group
INSERT INTO user_to_groups (user_id, group_id) VALUES
  ('seed_mod_001', 'seed_grp_supermod');

-- Regular user gets Standard Creator group
INSERT INTO user_to_groups (user_id, group_id) VALUES
  ('seed_user_001', 'seed_grp_creator');
