/**
 * Seed script — generates hashed passwords & outputs SQL for local D1 seeding.
 * Run:  node scripts/seed.mjs | npx wrangler d1 execute gamexamxi-db --local --file=-
 * Or:   node scripts/seed.mjs > drizzle/seed.sql && npx wrangler d1 execute gamexamxi-db --local --file=drizzle/seed.sql
 */
import { webcrypto } from 'node:crypto'

const crypto = webcrypto

async function hashPassword(password) {
  const encoder = new TextEncoder()
  const salt = crypto.getRandomValues(new Uint8Array(16))
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    encoder.encode(password),
    'PBKDF2',
    false,
    ['deriveBits']
  )
  const derivedBits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations: 100_000, hash: 'SHA-256' },
    keyMaterial,
    256
  )
  const hashArray = new Uint8Array(derivedBits)
  const saltHex = Array.from(salt).map(b => b.toString(16).padStart(2, '0')).join('')
  const hashHex = Array.from(hashArray).map(b => b.toString(16).padStart(2, '0')).join('')
  return `${saltHex}:${hashHex}`
}

// Simple cuid2-like IDs for seeding (not cryptographically unique but fine for dev)
function seedId(label) {
  const ids = {
    admin: 'seed_admin_001',
    mod: 'seed_mod_001',
    user: 'seed_user_001',
    group_creator: 'seed_grp_creator',
    group_supermod: 'seed_grp_supermod',
    item_player_1: 'seed_player_001',
    item_team_1: 'seed_team_001',
    item_tournament_1: 'seed_tournament_001',
  }
  return ids[label]
}

async function main() {
  const now = Date.now()

  const adminHash = await hashPassword('AdminPass123!')
  const modHash = await hashPassword('ModPass123!')
  const userHash = await hashPassword('UserPass123!')

  const sql = `
-- ============================================
-- SEED DATA — generated by scripts/seed.mjs
-- ============================================

-- Clear existing seed data (idempotent)
DELETE FROM user_to_groups;
DELETE FROM point_transactions;
DELETE FROM permission_groups;
DELETE FROM users;

-- ==================
-- Users
-- ==================
INSERT INTO users (id, email, name, account_role, role, password_hash, created_at, updated_at) VALUES
  ('${seedId('admin')}', 'admin@example.com', 'Dev Admin', 'admin', 'root',  '${adminHash}', ${now}, ${now}),
  ('${seedId('mod')}',   'mod@example.com',   'Dev Mod',   'user',  'mod',   '${modHash}',   ${now}, ${now}),
  ('${seedId('user')}',  'user@example.com',  'Dev User',  'user',  'user',  '${userHash}',  ${now}, ${now});

-- ==================
-- Permission Groups
-- ==================
INSERT INTO permission_groups (id, name, permissions, created_at) VALUES
  ('${seedId('group_creator')}',  'Standard Creator', '["game:create","game:edit","item:create","item:view","item:edit"]', ${now}),
  ('${seedId('group_supermod')}', 'Super Mod',        '["game:all","user:moderate","points:grant","xp:grant","item:create","item:edit","item:delete","item:view","pickem:create","pickem:edit","pickem:delete","pickem:view"]', ${now});

-- ==================
-- User ↔ Group assignments
-- ==================
-- Mod gets Super Mod group
INSERT INTO user_to_groups (user_id, group_id) VALUES
  ('${seedId('mod')}', '${seedId('group_supermod')}');

-- Regular user gets Standard Creator group
INSERT INTO user_to_groups (user_id, group_id) VALUES
  ('${seedId('user')}', '${seedId('group_creator')}');

-- ==================
-- Item Events (Players, Teams, Tournaments)
-- ==================
INSERT INTO item_events (id, name, logo, description, link_social, level, parent_id, type, created_by, created_at, updated_at) VALUES
  ('${seedId('item_player_1')}', 'Faker', 'https://example.com/faker.jpg', 'Lee Sang-hyeok - Professional gamer from South Korea', '{"type":"twitter","url":"https://twitter.com/faker","handle":"@faker","isPublic":true}', 100, NULL, 'player', '${seedId('admin')}', ${now}, ${now}),
  ('${seedId('item_team_1')}', 'T1', 'https://example.com/t1.jpg', 'T1 Esports Organization', '{"type":"twitter","url":"https://twitter.com/T1","handle":"@T1","isPublic":true}', 50, NULL, 'team', '${seedId('admin')}', ${now}, ${now}),
  ('${seedId('item_tournament_1')}', 'Worlds 2024', 'https://example.com/worlds2024.jpg', 'League of Legends World Championship 2024', '{"type":"youtube","url":"https://youtube.com/lol","handle":"@lol","isPublic":true}', 0, NULL, 'tournament', '${seedId('admin')}', ${now}, ${now});
`.trim()

  console.log(sql)
}

main().catch(console.error)
