-- ============================================
-- SEED DATA ΓÇö generated by scripts/seed.mjs
-- ============================================

-- Clear existing seed data (idempotent)
DELETE FROM user_to_groups;
DELETE FROM point_transactions;
DELETE FROM permission_groups;
DELETE FROM users;

-- ==================
-- Users
-- ==================
INSERT INTO users (id, email, name, account_role, role, password_hash, created_at, updated_at) VALUES
  ('seed_admin_001', 'admin@example.com', 'Dev Admin', 'admin', 'root',  'b14f0897e3effeb82c9697f929203cc8:61a3c18ac9b8f5d4fb5589c1edcd60db299b0c008cebe528abc994efed6e951e', 1778073327063, 1778073327063),
  ('seed_mod_001',   'mod@example.com',   'Dev Mod',   'user',  'mod',   '41a75b2a3b8303b1947c43331e28369b:4a8909ad1fa14c78449c1313d833ba9b3ea63d11be611dab171666eabe7c11a4',   1778073327063, 1778073327063),
  ('seed_user_001',  'user@example.com',  'Dev User',  'user',  'user',  '514ddeffdc231d10dcd0e2531463b45b:975b6eb4a724f5006d6b93e9be3cbca71e1113f5c19f90f8f45495c60eca5846',  1778073327063, 1778073327063);

-- ==================
-- Permission Groups
-- ==================
INSERT INTO permission_groups (id, name, permissions, created_at) VALUES
  ('seed_grp_creator',  'Standard Creator', '["game:create","game:edit","item:create","item:view","item:edit"]', 1778073327063),
  ('seed_grp_supermod', 'Super Mod',        '["game:all","user:moderate","points:grant","xp:grant","item:create","item:edit","item:delete","item:view","pickem:create","pickem:edit","pickem:delete","pickem:view"]', 1778073327063);

-- ==================
-- User Γåö Group assignments
-- ==================
-- Mod gets Super Mod group
INSERT INTO user_to_groups (user_id, group_id) VALUES
  ('seed_mod_001', 'seed_grp_supermod');

-- Regular user gets Standard Creator group
INSERT INTO user_to_groups (user_id, group_id) VALUES
  ('seed_user_001', 'seed_grp_creator');

-- ==================
-- Item Events (Players, Teams, Tournaments)
-- ==================
INSERT INTO item_events (id, name, logo, description, link_social, level, parent_id, type, created_by, created_at, updated_at) VALUES
  ('seed_player_001', 'Faker', 'https://example.com/faker.jpg', 'Lee Sang-hyeok - Professional gamer from South Korea', '{"type":"twitter","url":"https://twitter.com/faker","handle":"@faker","isPublic":true}', 100, NULL, 'player', 'seed_admin_001', 1778073327063, 1778073327063),
  ('seed_team_001', 'T1', 'https://example.com/t1.jpg', 'T1 Esports Organization', '{"type":"twitter","url":"https://twitter.com/T1","handle":"@T1","isPublic":true}', 50, NULL, 'team', 'seed_admin_001', 1778073327063, 1778073327063),
  ('seed_tournament_001', 'Worlds 2024', 'https://example.com/worlds2024.jpg', 'League of Legends World Championship 2024', '{"type":"youtube","url":"https://youtube.com/lol","handle":"@lol","isPublic":true}', 0, NULL, 'tournament', 'seed_admin_001', 1778073327063, 1778073327063);
