/**
 * Seed script — generates hashed passwords & outputs SQL for local D1 seeding.
 * Run:  node scripts/seed.mjs | npx wrangler d1 execute gamexamxi-db --local --file=-
 * Or:   node scripts/seed.mjs > drizzle/seed.sql && npx wrangler d1 execute gamexamxi-db --local --file=drizzle/seed.sql
 */
import { webcrypto } from 'node:crypto'

const crypto = webcrypto

async function hashPassword(password) {
  const encoder = new TextEncoder()
  const salt = crypto.getRandomValues(new Uint8Array(16))
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    encoder.encode(password),
    'PBKDF2',
    false,
    ['deriveBits']
  )
  const derivedBits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations: 100_000, hash: 'SHA-256' },
    keyMaterial,
    256
  )
  const hashArray = new Uint8Array(derivedBits)
  const saltHex = Array.from(salt).map(b => b.toString(16).padStart(2, '0')).join('')
  const hashHex = Array.from(hashArray).map(b => b.toString(16).padStart(2, '0')).join('')
  return `${saltHex}:${hashHex}`
}

// Simple cuid2-like IDs for seeding (not cryptographically unique but fine for dev)
function seedId(label) {
  const ids = {
    admin: 'seed_admin_001',
    mod: 'seed_mod_001',
    user: 'seed_user_001',
    group_creator: 'seed_grp_creator',
    group_supermod: 'seed_grp_supermod',
  }
  return ids[label]
}

async function main() {
  const now = Date.now()

  const adminHash = await hashPassword('AdminPass123!')
  const modHash = await hashPassword('ModPass123!')
  const userHash = await hashPassword('UserPass123!')

  const sql = `
-- ============================================
-- SEED DATA — generated by scripts/seed.mjs
-- ============================================

-- Clear existing seed data (idempotent)
DELETE FROM user_to_groups;
DELETE FROM point_transactions;
DELETE FROM user_points;
DELETE FROM user_stats;
DELETE FROM permission_groups;
DELETE FROM users;

-- ==================
-- Users
-- ==================
INSERT INTO users (id, email, name, role, password_hash, created_at, updated_at) VALUES
  ('${seedId('admin')}', 'admin@example.com', 'Dev Admin', 'admin', '${adminHash}', ${now}, ${now}),
  ('${seedId('mod')}',   'mod@example.com',   'Dev Mod',   'mod',   '${modHash}',   ${now}, ${now}),
  ('${seedId('user')}',  'user@example.com',  'Dev User',  'user',  '${userHash}',  ${now}, ${now});

-- ==================
-- Permission Groups
-- ==================
INSERT INTO permission_groups (id, name, permissions, created_at) VALUES
  ('${seedId('group_creator')}',  'Standard Creator', '["game:create","game:edit"]', ${now}),
  ('${seedId('group_supermod')}', 'Super Mod',        '["game:all","user:moderate","points:grant","xp:grant"]', ${now});

-- ==================
-- User ↔ Group assignments
-- ==================
-- Mod gets Super Mod group
INSERT INTO user_to_groups (user_id, group_id) VALUES
  ('${seedId('mod')}', '${seedId('group_supermod')}');

-- Regular user gets Standard Creator group
INSERT INTO user_to_groups (user_id, group_id) VALUES
  ('${seedId('user')}', '${seedId('group_creator')}');

-- ==================
-- User Points (init balances)
-- ==================
INSERT INTO user_points (user_id, balance, point_limit) VALUES
  ('${seedId('admin')}', 0, 10000),
  ('${seedId('mod')}',   0, 10000),
  ('${seedId('user')}',  500, 10000);

-- ==================
-- User Stats / XP
-- ==================
INSERT INTO user_stats (user_id, current_xp, current_level) VALUES
  ('${seedId('admin')}', 0, 1),
  ('${seedId('mod')}',   0, 1),
  ('${seedId('user')}',  250, 1);
`.trim()

  console.log(sql)
}

main().catch(console.error)
